- xAPI.md
> No formatting in language map strings.

- xAPI.md
Relates to https://github.com/adlnet/xAPI-Spec/issues/501
This PR is **not ready to be merged** and is a work in progress. That said, I am trying to keep this in a state where it could be merged as an improvement after each commit by commenting out unfinished bit. I also appreciate comments on the general direction and specific changes so far.  
It may be that I get to a certain point with this and then put it on the back burner to focus on other, more quick-win, issues. In that event, it'd be worth merging to avoid conflicts.
> Remove SCORM dependancies

- README.md
Note: not an actual spec change, but will inform formatting in the future. 
Contributes to https://github.com/adlnet/xAPI-Spec/issues/488
> Additions to the style guide section of readme.md

- xAPI.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/481
Also replaced "of" with "taken by" for readability.
> Replace "Learner or Team Object" with "Actor"

- xAPI.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/495
In the end I decided to PR this separately from #563 because this should be a quick merge and #563 could require some discussion.
> Replace "field" with "property" or "parameter" as appropriate.

- xAPI.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/439
> eTag header for PUT/POST

- xAPI.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/579
> Improve section 5.4 description

- xAPI.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/575
> LRS can reject for its own reasons

- xAPI.md
Addresses https://github.com/adlnet/xAPI-Spec/issues/484
> Clarifications on Immutability

- xAPI.md
> Clarifications to section 7.8

- xAPI.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/335
I'm sure there'll be some debate on my use of MUST, SHOULD* and MAY* here.
> Clarify that extra properties are not allowed.

- xAPI.md
#599 fix and #574 standardising full stops after titles
> Two issue typo fix

- xAPI.md
> "Plain text body" error response fix

- xAPI.md
I believe this item was numbered incorrectly in the ToC
> Updated 2.2.3 to 2.3 in Reading Guidelines

- xAPI.md
Added "objectType": "Activity"
> Example SubStatement object missing objectType

- xAPI.md
> Clearer language for relative endpoints being required

- README.md
- xAPI.md
Fixes #494. 
This doesn't include every line in Andy's list as some of that stuff is already required.
> Prefer POST to PUT

- xAPI.md
> Delete duplicate "See" typo

- xAPI.md
> Revert "Update xAPI.md"

- xAPI.md
> LRS SHOULD* use other language maps if it has them. 

- xAPI.md
Fixes #635 as agreed in issue (word for word).
> Avoid phrase "stored received"

- xAPI.md
> Lack of signature, not timing or order, is important

- xAPI.md
> Attempt to clarify Filter Conditions for voiding statements

- xAPI.md
> Detail Attachment File URL

- xAPI.md
> Amend rationale for IFIs

- xAPI.md
> State API etags are only optional for clients not LRS

- xAPI.md
> Explain SHOULD*

- xAPI.md
Fixes #569 in line with consensus reached there.
> If there is no document, the new document must still be application/json

- xAPI.md
> Add concept of Metadata Provider/Consumer

- xAPI.md
> Specify content for all requests

- xAPI.md
> List headers and tidy whitespace in contents

- xAPI.md
Some big structural changes, but no meaning or behavioural changes are intended. In some cases I have deleted requirements where they are more clearly and sensibly covered elsewhere in the specification. I will add comments in the diff to explain. 
Please review carefully before merging. 
Fixes #637
> Re-work sections 6.4 and 6.4.1

- xAPI.md
Fixes #673
Fixes #667
Fixes #686
> typos and minor fixes

- xAPI.md
Fixes #675 - Duration meaning ambiguity
Fixes #672 - Make explicit that the LRS MUST validate signatures
> Two issues in section 4 

- xAPI.md
Works towards #544 
Please don't merge this until #645 merges as I believe this will conflict and this will be easier to re-do. Still valuable to discuss the wording of this PR though.
> Agent Profile API: Clarifications

- xAPI.md
> Issues #695 #696 #633 (Section 4)

- xAPI.md
> Issue #588 (Appendix)

- xAPI.md
> Issues #595 #668 (Section 6)

- xAPI.md
I'd like to switch this language to Roger's.  I plan on using some of
the text after that in future sections, so it could be deleted from this
section after the adding phase is over.
> Part1 section1

- xAPI.md
No additions, just changed numbering in 2.3-2.5
> Part2 section2.3 renumber

- xAPI.md
Looking at this probably need a little more intro text, but wanted to set some groundwork here and move onto thinking about other areas in Part 1 still.
> Part1 section3.0

- xAPI.md
> Revert "Part1 section8"

- xAPI.md
Added some intro text.  Left most sections intact, but will be combed for consistency (removal of Sub-API, for example) in the next pass.
> Part3 section2

- xAPI.md
These sections were essentially new, save for some HEAD documentation.
> Part3 section1and1.1

- xAPI.md
Should have all changes from @garemoko's PR
> Section1Part8(and9)RestoreGaremokosPR

- xAPI.md
A variety of formatting types updates.  Much of this was copied from other parts of the document with the intention of removing some, but likely duplicating so this section can serve as a reference point.
> Part2 section4 Additions

- xAPI.md
Moved current Section 2.1 text to 2.0.  Added new text to 2.1.
> Part2 section2.1 Restructure

- xAPI.md
Please change the language if anything is unclear.  Thanks for your help!
> Part1 section4

- xAPI.md
Probably needs a lot of work and clarity.  REST is largely conceptual and I'm not an expert in it.  Hope this is a good start.
> Part1 section5

- xAPI.md
Added intro text to 2.2.  Fixed some spelling errors in 2.2.1 as well.
> Part2 section2.2

- xAPI.md
Updated TOC to go across all 3 Parts - eventually will split into 3
documents after all links are done and the current "gray/coding" area
has a permanent home.
> Updated TOC to go across all 3 Parts

- xAPI.md
> Clarify what to do if LRS has no canonical activity definition

- xAPI.md
> explain correct response pattern empty array meaning

- xAPI.md
In this proposed revision, I am trying to concentrate on the broader picture of the xAPI is designed to be used and have eliminated the paragraphs describing how the interoperability works. I think that is explained below.
> Introduction

- xAPI.md
> Nicer description of actor

- xAPI.md
Tackles issues #719 #729 #731 and #733
> Fix1.03 iri timestamp duration

- xAPI.md
If I recall correctly, the agreement on #658 was to simply update the reference to RFC 1341 to 2046. This PR does that.
> Update RFC 1341 to 2046

- xAPI.md
Note that I edited the wrong section at first, however I think that's still an improvement. Comments welcome.
> Fixes Issue 682

- xAPI.md
> add case and order matters defaults

- xAPI.md
> Characterstring parameters not validated

- xAPI.md
> recommended to also populate optional properties where relevant

- xAPI.md
> Re-add paragraphs on how xAPI promotes interoperbility

- CONTRIBUTING.md
Missing @phamdt (no known real name)
This now includes everybody who has committed changes big and small to the latest version in the restructure branch. 
I didn't take the time to go through issues and find everybody who made a suggestion. If they want credit, they can ask to be listed :-)
Fixes #693
> Update contributors list from github data

- xAPI.md
Fixes #732 
Should be very uncontroversial as it's just matching the style of other tables in the document.
> capitalisation fix

- xAPI.md
> clearer code formatting in example

- xAPI.md
@andyjohnson another ninja-merge candidate
> Delete document re-org note

- xAPI.md
@andyjohnson I think you can ninja-merge this one.
> Fix Revision History link

- xAPI.md
> clarify changes to activity definition requirements

- xAPI.md
5.1 Interoperability Between Components was moved and edited in order to provide an explanation of parts two and three.
> Explain the three parts

- xAPI.md
See #798
The Requirements for Activity Providers which i removed are covered in the Metadata section.
> Many tweaks in Part 2

- xAPI.md
Ok, used Vim without any special Markdown support this time, a git diff shows no whitespace issues that I can tell, but you might want to double check @garemoko.
Hopefully this is the last time I need to resubmit, darn whitespace inconsistencies!
> Once more, with feeling

- xAPI.md
Suggestions of improvements to the wording here are very welcome.
> State link between registration statement property and it's use within the State resource

- xAPI.md
> Add link to metadata section in IRIs section

- xAPI.md
Making the spec it a little more en-US.
> Whilst to While

- xAPI.md
Fixes #785
@jhaag75 - does this address everything you wanted to cover in that issue?
> Update verb example

- xAPI.md
Addresses #800. Does not address #848.
> Edits to introduction

- xAPI.md
> Replace "cannot use attachments" with "does not send the contents of attachments"

- xAPI.md
Based on conversations and feedback, changed the definitions only.  Any other changes will need to be reflected here, so it made sense to start here.  Note especially the change to "Client" and please make sure things still make sense.
> Changed Definitions

- xAPI-About.md
> re-add part 1 title

- xAPI-About.md
> How the LRS knows that these  multiple personas belong to a single person is out of scope

- xAPI-Data.md
> Fix example timestamps

- xAPI-Data.md
> No component lists supported

- xAPI-Data.md
This has a little wordsmithing and some vocabulary updating, some white space fixing, and capitalization fixes.
> 1.0.3 Sections 2.1-2.3 in Data

- xAPI-Data.md
Fix #897 (and a stray extra bullet).
> ISO 8601 should* also be RFC 3339

- xAPI-Data.md
This is a re-do of #902. 
Please check carefully even though #902 already had two +1s
> re-do PR #902

- xAPI-Communication.md
Check the individual commits for comments.  Nothing too drastic.  I did change "call" to "request" in some places, which I thought more acceptable.  As with anything in these, please point out if I did something wrong.
> 1.0.3 communication edits

- xAPI-About.md
- xAPI-Data.md
> 1.0.3 move one requirement per 913

- xAPI-Data.md
@jhaag75 original text https://github.com/adlnet/xAPI-Spec/issues/921#issuecomment-217028522,  incorporating suggestions from @fugu13, plus a few of my own adjustments
> Advice on language tags - fixes #921

- xAPI-Data.md
I also changed client to LRP because these requirements relate to generating data only.
> Fix issue #924

- xAPI-Data.md
This is intended to resolve https://github.com/adlnet/xAPI-Spec/issues/931.
> Clarify Stored Requirements

- xAPI-Communication.md
- xAPI-Data.md
This PR corrects a bad closing row tag and a missing opening row tag in two tables, and adjusts the corresponding row anchors to be consistent.
> Fix formatting on two tables

- xAPI-Communication.md
> Order matters for statement ids returned after POST

- xAPI-Communication.md
> responses also use application/json

- xAPI-Communication.md
> Remove note about LRS fetching statements from client

- xAPI-Communication.md
> X-Experience-API-Consistent-Through is latest timestamp, not just any timestamp

- xAPI-Data.md
> Specify that the signature is an attachment

- xAPI-About.md
Nothing too tough in here.  A couple words were changed for intent and to be consistent with the rest of the document.
> 1.03 grammar style about

- xAPI-Communication.md
I realized I didn't have a new branch when I started editing the first lines and navigated away, figuring it would cancel.  That first commit may be that.  I simply repeated in the next commit, so hopefully nothing wonky happened in there.  Look in each commit for notes.  Thanks!
> 1.3 grammar style on communication

- xAPI-Communication.md
Fixed a MUST in normative language - moved into a requirement.
> Stray OAuth Requirement

- xAPI-About.md
Fixes #968.
Possibly conflicts #961 and should be merged after.
> diagrams text edits

- xAPI-About.md
- xAPI-Communication.md
> Distinguish Profiles from the Agent and Activity Profile Resources

- xAPI-About.md
- xAPI-Communication.md
- xAPI-Data.md
- xAPI.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/981
> Remove "(xAPI)" in part 2 header

- xAPI-Data.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/989
> z not s and delete "above"

- README.md
I missed a bit: https://github.com/adlnet/xAPI-Spec/pull/983#issuecomment-243259859
> Also remove (xAPI) in readme.md

- xAPI-Data.md
Typos, punctuation, deprecations, etc.
> Miscellaneous Minor Fixes

- xAPI-Data.md
> Spelling Update

- xAPI-Data.md
Implements #982; see discussion at https://github.com/adlnet/grail-issue-tracker/issues/27
This hasn't has any spec discussion yet. I'd be very interested in input from @bscSCORM / @brianjmiller / @oconnetf before this merges.
> Be more general in LRS data type validation requirements

- xAPI-Data.md
> rebase PR 1035 to dev

- xAPI-About.md
Updates to align with new profile spec guidance.
> Profile Spec Updates

- README.md
I think it is worth adding a link to the updated version, since there are many resources online and one can get confused when doing research on xAPI concepts .
> update README.md (xAPI version)
