- xAPI.md
Fix https://github.com/adlnet/xAPI-Spec/issues/471#issuecomment-67382428 as agreed on yesterdays call. 
Also addresses two other occurrences of the word "blank" in the spec. 
Also tidies up some lowercase shoulds around timestamp and authority.
> Removes the ambiguous word "blank" in 3 places.

- xAPI.md
We had a little debate here yesterday about verb metadata. This PR represents my personal view on what's implied as the way verb metadata can and must be handled. I see this as just clarifications, rather than new requirements, but I think that's open to debate.
Let's discuss!
> Add clarity to use of verb metadata

- xAPI.md
Fixes #477. 
Note that the consensus between @fugu13 and @nashyura in the issue was that this requirement should be a MUST. I disagree for the following reasons:
* Russell mentioned that Wax supports the alternate format and has users using it. This is going to be a breaking change for those users. 
* The alternative format is allowed under ISO 8601 so long as there is agreement between the communicating parties. On that basis, I don't see how an LRS can be non-conformant for receiving alternate format durations. It could be flagged as non-conformant for returning alternative format durations as presumably the test suite does not have prior agreement to accept that format. Equally, a test suite for content could brand content non-conformant for sending using that format. 
I've used …
> Clarify ISO 8601 duration

- xAPI.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/563
Also fixes https://github.com/adlnet/xAPI-Spec/issues/495 as it incorporates https://github.com/adlnet/xAPI-Spec/pull/591 to avoid conflict. 
Where may/should/must have already been replaced in outstanding PRs I've tried not to change those lines to avoid conflict. 
In two places I replaced 'should' with 'MUST' as i didn't see any other possible behaviour. 
I deleted two blocks of text which were simply parroting what was already in requirements elsewhere, one of which was parroting an old set of requirements that had been reworded and improved. 
edit: changed 'three' to 'two'
> replace lowercase may/should/must

- xAPI.md
I think most of this is pretty straightforward.  I just moved information which was in the table in 4.1 to these sections.  The one bullet that needs a look at is 
An LRS MUST ignore any value the Statement's stored property has when handling requests.
While the spec says the stored property is set by the LRS, we don't actually say what happens if it is used by an AP, etc.  I'm thinking we can't flat-out reject any Statement with "stored" because we expect LRS to LRS Statement transfers.  Ignoring makes sense, especially because "stored" is updated when transferred to a new system (per Appendix D).
> Update Sections 4.1.7 and 4.1.8 with 4.1 Table Information

- README.md
Hey Everyone,
I've tried to be more specific on how we should use styles within the spec, specifically double quotes, single quotes, lack of quotes (i.e. just describing concepts), and code.  All opinions are welcome.  
I looked at our use of single quotes and here is the data I pulled:
Most uses of single quotes were as apostrophes or as quotes within quotes, which are acceptable.
The other uses were:
9 uses as a specific property or parameter (recommend double quotes)
2 uses as specific values which would be returned/used by code (recommend coding style)
10 uses as naming something or providing clarification that it is a concept in the document rather than simply the word (examples are 'Long', 'Short', and 'About')  These are correct uses.
I've earmarked these for a future PR and will …
> Clarification of Styles

- xAPI.md
Aims to solve #558. 
I didn't even look at the instances of "1.0.0", on the assumption that when we did 1.0.1, we left some at 1.0.0 deliberately and correctly :-)
> 1.0.1 changes to "latest patch version".

- xAPI.md
Fixes #536
I may have gone off piste with formatting here. Feel free to critique.
> Clarify values of boolean parameters in GET Statements

- xAPI.md
Fixes #513 
The issue also applied to content-length so I fixed this in a more generic way, by adding an extra column to the table to match parameters to properties and saying that they always have to match.
> Attachment parameters and properties MUST match!

- xAPI.md
Fixes #501 
Fixes #603 following @fugu13's proposed solution. I quite like that we're allowing single numbers because it means the requirements are the same for learner response and correct response.
> More SCORM dependancy removal

- xAPI.md
Fixes #653 
Also amends the details relating to attachments in that section as discussed in the comments of #653.
> Rename section 7.8 to Alternate Request Syntax

- xAPI.md
Fixes #659.
Also changes the heading within the Agent Profile API to be consistent with the other two and less confusing!
> Specify the type of ids returned by Multiple Document GET

- xAPI.md
Fixes #629.
IMHO we need to explicitly state that the scaled and raw are not related by any specific mechanism in order to avoid the assumption that they are.
Note that the text being changed is within 1.0.3, so whilst this looks like a breaking change, it's actually **preventing** a breaking change that slipped through the net!
> Amendments to SCORM dependancy removal text

- xAPI.md
Fixes #557 
My honest view on this though is that this PR isn't required and that the issue can simply be closed. The fact that sha2 is listed as required and fileUrl is listed as optional is pretty clear to me that sha2 is always required. 
Now we have a PR, hopefully the issue can be closed either way!
> Explicitly state sha2 is always always required for attachments.

- xAPI.md
This PR is a rebase of #681 which was based on `master` and a PR to `master`. This one bases off `1.0.3` and adds similar content with some clarification based on feedback.
Here's the original PR text:
> When I was going through the specification it was completely unclear to me that the State APIs have concurrency requirements associated with them. It wasn't until I was going to put in an issue to talk about adding the feature that I noticed the mention in the Concurrency section.
> All that I did was simply callout in the State API section that there are requirements for each of the State APIs that must be met for concurrency that way it is more clear that there's more to the State APIs than just what is listed there.
> Call Out Concurrency Controls for Document APIs

- xAPI.md
* Fixes #638 via a different approach than #662 
* Explicitly states that non-LRS systems can implement one or more LRS endpoints/methods and gives an example. Clarifies that systems which do so are not LRSs. I added this in this PR because I was starting to go down this route in the definition of reporting systems and felt it didn't belong in a definition.
> remove all reference to reporting systems/tools

- xAPI.md
> Four issues in section 7

- xAPI.md
Added some text to extending.  Likely we can eliminate text in a couple
other stray areas.    The text in the later portion of 8.3 should be
updated to refer to all "coinable" xAPI constructs.
> Part1 section8

- xAPI.md
Fixes #588 
Possibly controversial points:
* The word "approximately" on line 2797
* Lines 2805 and 2806
* The lack of period in the braced sentence on line 2789
@fugu13 as you've been involved in the #588 discussion hopefully this is a quick one for you to review.
> Add duration examples

- xAPI.md
Fixes #746
Also added Correct Responses Pattern heading, deleted "Note that" and added a missing 's' on line 1568.
> Correct Responses Pattern should be exhaustive but may not be

- xAPI.md
These required/optional columns were added in 1.0.2. Since 1.0.0 and maybe before we have had the requirement ```Interaction Activities MUST have a valid interactionType.```. Therefore the "optional" in 1.0.2 is a typo and should be corrected in this version.
> Interaction type should be required

- CONTRIBUTING.md
- README.md
- xAPI.md
This is the results of a spell check across all three files. Whilst most of these are obvious fixes, some might be controversial such as:
* "un-ordered" to "unordered"
* "who" to "whom"
I'm happy to change either of those back if somebody feels strongly. 
For some reason the copy-paste process back and forwards to the spell checker has led to a small number of space characters getting replaced with a different space character, e.g. line 1017. I'm not sure why this is, but I don't think it matters. 
Fixes #612
> Spell check. 

- xAPI.md
fixes #784
I didn’t add the time zone to the example signed statement as I didn’t
want to mess with the signature.
> add id, timestamp and time zone to appendix examples

- CONTRIBUTING.md
I found out who he was just after the other PR merged. He was working for Saltbox at the time he made the contributions but now isn't working in edtech at all so I left the org column blank.
> Add @phamdt

- xAPI.md
I'm unable to find a reference for the LMS definition - I'm hitting citogenesis. I've just to fixed the formatting issue and left it without a link.
> fix formatting of LMS definition

- xAPI.md
Note: separately we need to go through all the bulleted lists in the document and standardize the line breaks. Most lists do not have line breaks between bullets.
> Fix bullets in 2.2.1.2 POST Statements

- xAPI.md
This doesn't really make a lot of sense because if you are using a URL, it will be an IRI. I think the first sentence is sufficient.
> Remove confusing and superfluous sentence from definition

- xAPI.md
* Moved paragraph from the middle to the start of part 3. 
* Changed reference from 'Sections 6 and 7' to part 3.
* Libraries are now available, not under development.
* Changed "content developers" to "Activity Provider developers".
> Move suitable introduction to part 3 to become the part 3 introduction (and tweak wording)

- xAPI.md
See https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#encoding
I have a feeling we said on the call that we'd create a strings data type section and put this there, but I don't think that's right. I think this is broader than strings as values of properties and includes strings containing JSON objects.
> Re-add dropped encoding section

- xAPI.md
This heading doesn’t make sense here and the description basically repeats the text immediately above.
> Delete 'Use in Communities of Practice' section

- xAPI.md
According to git blame, this requirement got duplicated here in a commit by @andyjohnson but looking at that commit, it doesn't include this line. I wonder if maybe it snuck in during some conflict fixing or something, but it's annoying that blame doesn't pick that up. 
However it got here though, this requirement shouldn't have been copied here and needs to go.
> Remove extra requirement that seems to have been duplicated by a git bug

- xAPI.md
These removed requirements were significantly overlapping requirements in the metadata section in Part 3, which is a better home for them rather than Part 1. I removed the first requirement as a duplicate and edited the second to match the related existing requirement. 
This is the first tick in #798.
> Merge 'Requirements for Communities of Practice' into '3.2 Hosted Metadata'

- CONTRIBUTING.md
- README.md
This is an intial commit tackiling low-hanging fruit to get the spec docs passing markdown linting, so that any contributor with any editor can reliably edit the various pieces.
I tackled README.md first since it had few issues, just formatting things like whitespace and blank lines around headers and lists. It now passes the linter without complaint. 
Please see #829 for details; the goal is to set up CI testing so that PRs pass the linter prior to inclusion, this is a first pass on low-hanging fruit.
> Format Markdown docs to pass linter

- xAPI.md
@andyjohnson it;s possible that #730 was already resolved, but if not, does this PR address any remaining issue?
I've literally copied and pasted some of line 596 down to line 1073 in order to keep the language consistent. 
The two sections do seem a little contradictory in that one says the display is usually in the past tense and the other says it can be in another tense, however those two things are both true and in line with the point being made in their respective contexts.
> Tidy up past tense language

- xAPI.md
Fixes #736 
If you are using JWS JSON Serialization instead of JWS Compact Serialization to sign statement or verify signed statements, now is the time to speak up.
> Use JWS Compact Serialization please.

- xAPI.md
We already make the big changes from Document APIs to Resource APIs. This PR finishes the job. Includes a search through the document for all occurrences of “ API”.
I also changed some instances of "endpoint" to "resource" or "resource endpoint" and some "API consumer"s to "client"s. 
Please check carefully!
> Complete move from APIs to Resources

- xAPI.md
The reason the original requirement is a `SHOULD` instead of a `MUST` is to avoid unreasonably burdening distributed systems, which are not going to be able to reasonably perform such a check. However, this requirement doesn't add an unreasonable burden for such systems when applied only within the scope of a single batch, so there is no reason it shouldn't be a `MUST` there, so I'm suggesting we make it a `SHOULD*` in that particular case.
This came up as a result of the discussion here: https://github.com/adlnet/xAPI_LRS_Test/issues/54
> strengthened duplicate requirement in batches

- xAPI.md
I know @andyjohnson said "no PRs" so I'm ok with re-doing this later, but I wanted to get it out. 
Our current multipart/mixed example breaks the HTTP spec because it contains special characters not in quotes. Either we need to not use special characters, or we need to add quotes.
> Add quotes to boundry

- CONTRIBUTING.md
- xAPI-About.md
- xAPI-Communication.md
- xAPI-Data.md
- xAPI.md
I have changed all inline markdown syntax for version 1.0.3. (from ```` ```code``` to `code` ````)
> #838, Improve inline markdown syntax

- xAPI-Communication.md
> Explain why LRS is expected to use 'exact' when getting statements

- xAPI-Data.md
This is intended to resolve https://github.com/adlnet/xAPI-Spec/issues/909.
> Explicitly Note Hex Encoding Requirement for mbox_sha1sum

- xAPI-Communication.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/919
> LRS SHOULD* reject with 400 where the content type header does not match

- CONTRIBUTING.md
Fixes https://github.com/adlnet/xAPI-Spec/issues/988.
> Prefer "Total Learning Architecture"

- xAPI-About.md
The rendered Markdown looks awkward with the extra newline. Looks fine without.
> Remove Extra Newline

- xAPI-Communication.md
Fixes #980.
I ended up splitting this into two separate requirements. See commit history for the chain of thought. 
I think we're perfectly fine with this new requirement being a MUST because it's required to validate and reject requests based on the value of that header and the client MUST include it.
> Add "or known to be 0.9 due to the  lack of a version header"

- xAPI-Communication.md
Fixes #959
I tried to keep the example as high level as possible, but maybe it's still too detailed? 
Should I delete "; disabling the Document APIs entirely is not"?
> Implementers can break conformance for security reasons

- CONTRIBUTING.md
- xAPI-About.md
- xAPI-Data.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
> Fix broken headings in Markdown files

- CONTRIBUTING.md
Add blank lines and spaces to correct rendering of headers
> Format tweaks

- xAPI-Communication.md
Removed the extra "statementId" parameter from the alternate syntax request example.
> The intended xAPI method MUST be included as the value of the "method" query string parameter.
> The Learning Record Provider MUST NOT include any other query string parameters on the request.
duplicate of https://github.com/adlnet/xAPI-Spec/pull/1059 , as requested
> Removed extra qs parameter alt syntax example

- xAPI-Data.md
This removes an extra blank line that caused a bug in the rendering of the table on GitHub.
> Correct rendering in 2.5.s2 table

- xAPI-Data.md
According to ISO 8601 the time designator (T) precedes the time components.
Therefore P16559.14S is invalid and it should be PT16559.14S.
> Fix invalid ISO 8601 example

- xAPI-Data.md
Change 'equivelent' to the corrent 'equivalent'
> Fix typo in xAPI-Data.md

- xAPI-Communication.md
Fixes the alternative syntax request example in Appendix C: Cross Domain Request Example.
Section 1.3 Alternate Request Syntax states that: 
`
The Learning Record Provider MUST NOT include any other query string parameters on the request.
`
> Fix alternative syntax request example
